export default {
  NONE_EMPTY: '비워둘 수 없습니다.',
  INVALID_EMAIL: '올바른 이메일 형식이 아닙니다.',
  PASSWORD_CONFIRM_NOT_MATCH: '입력하신 비밀번호와 일치하지 않습니다.',
  PASSWORD_NOT_MATCH: '비밀번호가 일치하지 않습니다.',
  TOO_LONG_PASSWORD: '비밀번호는 최대 20자까지 가능합니다.',
  TOO_LONG_PASSWORD_CONFIRM: '비밀번호 확인은 최대 20자까지 가능합니다.',
  EXISTED_EMAIL: '이미 가입된 이메일입니다.',
  NOT_EXISTED_EMAIL: '존재하지 않는 이메일입니다.',
  NOT_EXISTED_INTERVIEW: '존재하지 않는 인터뷰입니다.',
  NOT_ALLOWED_JOIN_TO_INTERVIEW: '인터뷰어나 마스터는 인터뷰이로 참가할 수 없습니다.',
  NOT_EXISTED_SESSION: '존재하지 않는 세션입니다.',
  NOT_ALLOWED_UPDATE_SESSION: '세션을 수정할 권한이 없습니다.',
  NOT_MOBILE_NUMBER: '올바른 전화번호가 아닙니다.',
  TOO_LONG_QUESTION_TITLE: '질문의 길이는 최대 100자까지 가능합니다.',
  TOO_LONG_QUESTION_DESCRIPTION: '질문의 설명은 최대 500자까지 가능합니다.',
  NOT_ALLOWED_QUESTION_TYPE: '질문의 타입은 [file, text, radio, checkbox]만 가능합니다.',
  NOT_EXISTED_QUESTION_VALUES: '질문의 타입이 [radio, checkbox]일때 values는 항상 있어야 합니다.',
  NOT_ALLOWED_QUESTION_VALUES: '질문의 values는 string[]만 가능합니다.',
  NOT_EXISTED_QUESTION_LIMIT: '타입이 text일 때 답변의 최대 길이는 꼭 있어야 합니다.',
  TOO_LONG_QUESTION_LIMIT: '답변의 최대 길이는 10000자까지 가능합니다.',
  NOT_ALLOWED_UPSERT_QUESTION: '권한이 없습니다. 마스터 권한만 작업이 가능합니다',
  NOT_ALLOWED_GET_QUESTIONS: '질문 목록을 불러올 권한이 없습니다.',
  NOT_EXISTED_QUESTION: '존재하지 않는 질문입니다.',
  NOT_ALLOWED_CREATE_ANSWER: 'interviewee만 답변을 저장할 수 있습니다.',
  TOO_LONG_ANSWER_LENGTH: '답변의 길이가 질문의 제한보다 깁니다.',
  NOT_ALLOWED_FILE: '파일을 올릴 수 있는 질문이 아닙니다.',
  NOT_EXISTED_ANSWER_VALUES: '질문 타입이 [radio, checkobx]일 때 답변에 values는 항상 있어야 합니다',
  NOT_ALLOWED_ANSWER_VALUES: '질문의 values는 string[]만 허용합니다.',
  NOT_ALLOWED_MULTIPLE_VALUES: '[radio] 타입의 질문 답변의 values는 길이가 항상 1이어야 합니다.',
  NOT_EXISTED_ANSWER: '존재하지 않는 답변입니다.',
  NOT_ALLOWED_CREATE_FILE: '파일을 올릴 수 있는 사용자가 아닙니다.',
  TOO_LONG_SESSION_NAME: '이름은 최대 20자까지 가능합니다.',
  NOT_ALLOWED_PUBLISHING_SESSION: '제출을 할 수 없습니다. 세션 정보에 빈 칸이 있는지 확인해주세요.',
  NOT_ALLOWED_UPSERT_ANSWER_AFTER_PUBLISHED: '제출을 한 뒤로는 수정할 수 없습니다.',
  NOT_ALLOWED_UPDATE_SESSION_AFTER_PUBLISHED: '제출을 한 뒤로는 수정할 수 없습니다.',
  NOT_ALLOWED_INVITE_INTERVIEW: 'interviewer로 초대는 master만 할 수 있습니다.',
  NOT_ALLOWED_INVITE_SELF: '자기 자신을 초대할 수 없습니다.',
  NOT_EXISTED_USER: '존재하지 않는 유저입니다.',
}
